SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXIST AZIENDA;
DROP TABLE IF EXIST SEDE;
DROP TABLE IF EXIST DIPENDENTE;
DROP TABLE IF EXIST IMPIEGATO;
DROP TABLE IF EXIST AGENTE;
DROP TABLE IF EXIST CONTABILE;
DROP TABLE IF EXIST AZIENDA_CLIENTE;
DROP TABLE IF EXIST SEDE_CLIENTE;
DROP TABLE IF EXIST RAPPRESENTANTE;
DROP TABLE IF EXIST CONTRATTO;
DROP TABLE IF EXIST SPESE;
DROP TABLE IF EXIST AFFITTO;
DROP TABLE IF EXIST UFFICIO;
DROP TABLE IF EXIST TASSE;
DROP TABLE IF EXIST FORNITORI;
DROP TABLE IF EXIST SERVIZIO;
DROP TABLE IF EXIST IM_SE;
DROP TABLE IF EXIST CARTELLONI;
DROP TABLE IF EXIST VOLANTINI;
DROP TABLE IF EXIST STRISCE_ADESIVE;
DROP TABLE IF EXIST SPOT_RADIO;
DROP TABLE IF EXIST STAZIONE_RADIO;

CREATE TABLE AZIENDA (
Piva CHAR (11) PRIMARY KEY);

CREATE TABLE SEDE (
Via VARCHAR (70),
Numero_Civico SMALLINT,
Città VARCHAR (50),
Regione VARCHAR (50),
Provincia VARCHAR (50),
Piva CHAR (11) PRIMARY KEY,
FOREIGN KEY (Piva) REFERENCES AZIENDA (Piva));

CREATE TABLE DIPENDENTE (
CF CHAR (16) PRIMARY KEY,
Nome VARCHAR (50),
Cognome VARCHAR (50),
Stipendio INT,
Dirigente BOOLEAN,
Azienda CHAR (11),
FOREIGN KEY (Azienda) REFERENCES AZIENDA(Piva) );

CREATE TABLE IMPIEGATO (
CF CHAR (16) PRIMARY KEY,
FOREIGN KEY (CF) REFERENCES DIPENDENTE (CF));

CREATE TABLE agente (
NumeroID INT PRIMARY KEY, 
CF CHAR (16),
FOREIGN KEY (CF) REFERENCES DIPENDENTE (CF));

CREATE TABLE contabile(
CF CHAR (16) PRIMARY KEY,
FOREIGN KEY (CF) REFERENCES DIPENDENTE (CF));
	
CREATE TABLE azienda_cliente(
Piva CHAR (11) PRIMARY KEY,
Nagente INT NOT NULL,
FOREIGN KEY (Nagente) REFERENCES agente (NumeroID));

CREATE TABLE SEDE_CLIENTE(
Via VARCHAR (70),
Numero_Civico SMALLINT,
Città VARCHAR (50),
Regione VARCHAR (50),
Provincia VARCHAR (50),
Piva CHAR (11) PRIMARY KEY,
FOREIGN KEY (Piva) REFERENCES azienda_cliente (Piva));

CREATE TABLE RAPPRESENTANTE (
CF CHAR (16) PRIMARY KEY,
Nome VARCHAR (50),
Cognome VARCHAR (50),
Ruolo ENUM ('Amministratore','Propietario'),
Azienda CHAR (11),
FOREIGN KEY (Azienda) REFERENCES azienda_cliente(Piva));

CREATE TABLE CONTRATTO (
Codice INT PRIMARY KEY,
Tipo ENUM('a provvigione','a tempo'),
Pagamento ENUM ('bonifico','assegno','contanti'),
Piva CHAR (11),
Servizio INT,
Data INT,
FOREIGN KEY (Piva) REFERENCES AZIENDA_CLIENTE (Piva),
FOREIGN KEY (Servizio) REFERENCES SERVIZIO (Codice));

CREATE TABLE SPESE (
Codice INT AUTO_INCREMENT,
Contabile CHAR (16),
Azienda CHAR (11),
Anno INT,
PRIMARY KEY (Codice, Contabile, Azienda),
FOREIGN KEY (Contabile) REFERENCES Contabile(CF),
FOREIGN KEY (Azienda) REFERENCES Azienda(Piva));


CREATE TABLE AFFITTO (
Costo INT,
Codice INT PRIMARY KEY,
FOREIGN KEY (Codice) REFERENCES SPESE (Codice));

CREATE TABLE UFFICIO (
Costo INT,
Codice INT PRIMARY KEY,
Tipo VARCHAR (100),
Quantità INT,
FOREIGN KEY (Codice) REFERENCES SPESE (Codice));

CREATE TABLE TASSE (
Costo INT,
Codice INT PRIMARY KEY,
Tipo VARCHAR (100),
FOREIGN KEY (Codice) REFERENCES SPESE (Codice));

CREATE TABLE FORNITORI (
Costo INT,
Codice INT PRIMARY KEY,
Tipo VARCHAR (100),
Quantità INT,
FOREIGN KEY (Codice) REFERENCES SPESE (Codice));

CREATE TABLE SERVIZIO (
Codice INT,
Costo INT,
Azienda CHAR (11),
PRIMARY KEY (Codice, Azienda),
FOREIGN KEY (Azienda) REFERENCES AZIENDA (Piva));

CREATE TABLE IM_SE (
CF CHAR (16),
Codice INT,
PRIMARY KEY (Codice, CF),
FOREIGN KEY (Codice) REFERENCES SERVIZIO (Codice),
FOREIGN KEY (CF) REFERENCES IMPIEGATO (CF));

CREATE TABLE CARTELLONI (
Quantità INT,
Servizio INT PRIMARY KEY,
FOREIGN KEY (Servizio) REFERENCES SERVIZIO(Codice));

CREATE TABLE VOLANTINI (
Quantità INT,
Servizio INT PRIMARY KEY,
FOREIGN KEY (Servizio) REFERENCES SERVIZIO(Codice));

CREATE TABLE STRISCE_ADESIVE (
Quantità INT,
Servizio INT PRIMARY KEY,
FOREIGN KEY (Servizio) REFERENCES SERVIZIO(Codice));

CREATE TABLE SPOT_RADIO(
Frequenza VARCHAR(20),
ID INT AUTO_INCREMENT PRIMARY KEY,
Orario_inizio TIME,
Orairio_fine TIME,
Servizio INT,
FOREIGN KEY (Servizio) REFERENCES SERVIZIO (Codice));

CREATE TABLE STAZIONE_RADIO(
Frequenza_radio FLOAT,
Nome CHAR (50) PRIMARY KEY,
ID INT,
FOREIGN KEY (ID) REFERENCES SPOT_RADIO (ID));
